config/routes.rb
Passaporte::Application.routes.draw do
  resources :profiles

  get "home/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => "home#index"

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  after_validation :geocode
  geocoded_by :geo_string

  def geo_string
    [university, city, country].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @profile = Profile.new
  end
end

app/controllers/profiles_controller.rb
# encoding: utf-8
class ProfilesController < InheritedResources::Base
  respond_to :html, :json
  layout false, only: :show

  def permitted_params
    params.permit(:profile => [:name, :email, :age, :course, :university, :city,
      :country, :transportation_tip, :housing_tip, :visa_tip, :cultural_tip,
      :feeding_tip, :other_tip, :latitude, :longitude])
  end

  def create
    create!(:notice => "Obrigado por contribuir! Logo logo sua experiência aparecerá aqui :)") { root_url }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/content/_about.html.erb
<div id="aboutModal" class="reveal-modal" data-reveal>
  <h2>Oi!</h2>
  <p class="lead">Nós somos o Diego, a Livia e a Marcelle.</p>

  <p>O Passaporte UFPR é nosso trabalho de conclusão
  de curso mas, mais que isso, é um site que todos
  gostaríamos de ter tido antes dos nossos intercâmbios.</p>

  <p>Sim, nós 3 fomos intercambistas pela UFPR. E nós 3
  percebemos que tem informações e dicas que só quem
  já viajou pode dar aos futuros intercambistas. Assim
  surgiu a ideia de reunirmos tudo isso em um só lugar,
  de uma maneira descolada e interativa.</p>

  <p>Nesse site voce vai encontrar nosso perfil e de tantos
  outros alunos que toparam colaborar nesse projeto.</p>

  <p>Queremos que cada vez mais esse seja um banco de
  dados super completo para que todos os alunos da
  Universidade possam usufruir. Assim, na volta do
  intercâmbio, o aluno consegue dividir sua experiência
  em um ambiente maior que um relatório acadêmico,
  onde todos podem acessar e interagir.</p>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/content/_how.html.erb
<div id="howModal" class="reveal-modal" data-reveal>
  <h2>Como navegar</h2>

  <p>Para utilizar a página Passaporte UFPR da melhor
  maneira você pode participar de diversas formas:</p>

  <ul>
    <li>
      Caso você queira pesquisar informações sobre
      lugares para os quais você pode realizar intercâmbio,
      você pode navegar pelo mapa-múndi e clicar nos pins
      que desejar. Para pesquisar por lugares que oferecem
      intercâmbio para um determinado curso, você pode
      digitar o curso desejado na barra de pesquisa.
    </li>

    <li>
      Caso você seja ex-intercambista da UFPR e queira
      dividir sua experiência, você pode clicar no botão
      "Colabore" e preencher um formulário com suas dicas.
    </li>
  </ul>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/content/_join.html.erb
<div id="joinModal" class="reveal-modal" data-reveal>
  <h2>Formulário para Colaborador</h2>
  <p>Olá! Primeiramente, obrigado por participar deste projeto dividindo um pouco da sua experiência como intercambista. Sua colaboração é muito importante para que cada vez mais os intercambistas da Universidade Federal do Paraná possam aproveitar ao máximo a experiência da mobilidade acadêmica. Preencha as lacunas a seguir e, se quiser, deixe seu email para que estudantes interessados possam entrar em contato. Caso queira, você também pode incluir uma foto sua (que tal uma bem bonita de quando você viajou?) Novamente, muito obrigado!</p>

  <%= form_for(@profile) do |f| %>
    <% if @profile.errors.any? %>
      <div class="row">
        <div id="error_explanation" class="large-12 columns">
          <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

          <ul>
          <% @profile.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="large-6 columns">
        <label>Nome</label>
        <%= f.text_field :name %>
      </div>
      <div class="large-6 columns">
        <label>Email</label>
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="row">
      <div class="large-4 columns">
        <label>Idade</label>
        <%= f.text_field :age %>
      </div>
      <div class="large-4 columns">
        <label>Curso</label>
        <%= f.text_field :course %>
      </div>
      <div class="large-4 columns">
        <label>Sua Foto</label>
        <input type="file" />
      </div>
    </div>

    <div class="row">
      <div class="large-4 columns">
        <label>Universidade de Destino</label>
        <%= f.text_field :university %>
      </div>
      <div class="large-4 columns">
        <label>Cidade</label>
        <%= f.text_field :city %>
      </div>
      <div class="large-4 columns">
        <label>País</label>
        <%= f.text_field :country %>
      </div>
    </div>

    <fieldset>
      <div class="row">
        <div class="large-4 columns">
          <label>Dicas de alimentação e compras</label>
          <%= f.text_area :feeding_tip %>
        </div>
        <div class="large-4 columns">
          <label>Dicas culturais</label>
          <%= f.text_area :cultural_tip %>
        </div>
        <div class="large-4 columns">
          <label>Demais dicas</label>
          <%= f.text_area :other_tip %>
        </div>
      </div>

      <div class="row">
        <div class="large-4 columns">
          <label>Dicas sobre passagens e visto</label>
          <%= f.text_area :visa_tip %>
        </div>
        <div class="large-4 columns">
          <label>Dicas de moradia e segurança</label>
          <%= f.text_area :housing_tip %>
        </div>
        <div class="large-4 columns">
          <label>Dicas de transporte</label>
          <%= f.text_area :transportation_tip %>
        </div>
      </div>
    </fieldset>

    <div class="row">
      <div class="large-12 columns">
        <%= f.submit 'Enviar', class: 'button right', id: 'sendJoin' %>
      </div>
    </div>

  <% end %>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/content/_links.html.erb
<div id="linksModal" class="reveal-modal" data-reveal>
  <h2>Links Úteis</h2>

  <p>UFPR:</p>

  <ul>
    <li><a href="http://www.ufpr.br">ufpr.br</a></li>
    <li><a href="http://facebook.com/UFPRoficial">facebook.com/UFPRoficial</a></li>
  </ul>

  <p>ARI:</p>

  <ul>
    <li><a href="http://www.internacional.ufpr.br">internacional.ufpr.br</a></li>
    <li><a href="http://facebook.com/ufprinternacional">facebook.com/ufprinternacional</a></li>
  </ul>

  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/content/_profile.html.erb
<div id="profileModal" class="reveal-modal" data-reveal>


  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/home/index.html.erb
<div id="main_map" class="dark"></div>

<!-- Modals -->
<%= render partial: 'content/about' %>
<%= render partial: 'content/links' %>
<%= render partial: 'content/how' %>
<%= render partial: 'content/join' %>
<%= render partial: 'content/profile' %>

<script type="text/javascript">
  var map = L.mapbox.map('main_map', 'livia.map-zbsobfzo').setView([-40, -40], 3);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Passaporte UFPR" %></title>

    <!-- Mapbox API -->
    <link href='//api.tiles.mapbox.com/mapbox.js/v1.4.0/mapbox.css' rel='stylesheet' />
    <!--[if lte IE 8]>
      <link href='//api.tiles.mapbox.com/mapbox.js/v1.4.0/mapbox.ie.css' rel='stylesheet' />
    <![endif]-->
    <script src='//api.tiles.mapbox.com/mapbox.js/v1.4.0/mapbox.js'></script>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'shared/navigation' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :university %><br>
    <%= f.text_field :university %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :transportation_tip %><br>
    <%= f.text_area :transportation_tip %>
  </div>
  <div class="field">
    <%= f.label :housing_tip %><br>
    <%= f.text_area :housing_tip %>
  </div>
  <div class="field">
    <%= f.label :visa_tip %><br>
    <%= f.text_area :visa_tip %>
  </div>
  <div class="field">
    <%= f.label :cultural_tip %><br>
    <%= f.text_area :cultural_tip %>
  </div>
  <div class="field">
    <%= f.label :feeding_tip %><br>
    <%= f.text_area :feeding_tip %>
  </div>
  <div class="field">
    <%= f.label :other_tip %><br>
    <%= f.text_area :other_tip %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Course</th>
      <th>University</th>
      <th>City</th>
      <th>Country</th>
      <th>Transportation tip</th>
      <th>Housing tip</th>
      <th>Visa tip</th>
      <th>Cultural tip</th>
      <th>Feeding tip</th>
      <th>Other tip</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.email %></td>
        <td><%= profile.age %></td>
        <td><%= profile.course %></td>
        <td><%= profile.university %></td>
        <td><%= profile.city %></td>
        <td><%= profile.country %></td>
        <td><%= profile.transportation_tip %></td>
        <td><%= profile.housing_tip %></td>
        <td><%= profile.visa_tip %></td>
        <td><%= profile.cultural_tip %></td>
        <td><%= profile.feeding_tip %></td>
        <td><%= profile.other_tip %></td>
        <td><%= profile.latitude %></td>
        <td><%= profile.longitude %></td>
        <td><%= profile.active %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="row">

  <div class="large-12 columns">
    <h1><%= @profile.name %> <small><%= @profile.age %> anos</small></h1>
  </div>

</div>

<div class="row">

  <div class="large-6 columns">
    <h3><%= @profile.course %> em <%= @profile.university %></h3>
  </div>
  <div class="large-6 columns">
    <h3><%= @profile.city %> / <%= @profile.country %></h3>
  </div>

</div>

<div class="row">

  <div class="large-12 columns"><hr></div>

</div>

<div class="row">

  <div class="large-4 columns">
    <h5>Dicas sobre passagem e visto:</h5>
    <p><%= @profile.visa_tip %></p>
  </div>
  <div class="large-4 columns">
    <h5>Dicas de moradia e segurança:</h5>
    <p><%= @profile.housing_tip %></p>
  </div>
  <div class="large-4 columns">
    <h5>Dicas de transporte:</h5>
    <p><%= @profile.transportation_tip %></p>
  </div>
  <div class="large-4 columns">
    <h5>Dicas de alimentação e compras:</h5>
    <p><%= @profile.feeding_tip %></p>
  </div>
  <div class="large-4 columns">
    <h5>Dicas culturais:</h5>
    <p><%= @profile.cultural_tip %></p>
  </div>
  <div class="large-4 columns">
    <h5>Demais dicas e sugestões:</h5>
    <p><%= @profile.other_tip %></p>
  </div>
</div>

<a class="close-reveal-modal">&#215;</a>

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Passaporte UFPR', root_url %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <!-- <ul class="right">
      <li class="has-form search">
        <div class="row collapse">
          <div class="large-10 small-10 columns">
            <input type="text" placeholder="Buscar universidades">
          </div>
          <div class="large-2 small-2 columns">
            <a href="#" class="button expand">
              <i class="fi-magnifying-glass"></i>
            </a>
          </div>
        </div>
      </li>
    </ul> -->

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#" data-reveal-id="aboutModal">Quem somos</a></li>
      <li class="divider"></li>
      <li><a href="#" data-reveal-id="linksModal">Links úteis</a></li>
      <li class="divider"></li>
      <li><a href="#" data-reveal-id="howModal">Como navegar</a></li>
      <li class="divider"></li>
      <li><a href="#" data-reveal-id="joinModal">Colabore</a></li>
    </ul>
  </section>
</nav>